// <autogenerated />
namespace Matrix_51__50__32_Input_32_Tracker
{
	partial class MainForm
	{
		/// <summary>
		/// Designer variable used to keep track of non-visual components.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		/// <summary>
		/// Disposes resources used by the form.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing) {
				if (components != null) {
					components.Dispose();
				}
			}
			base.Dispose(disposing);
		}
		
		/// <summary>
		/// This method is required for Windows Forms designer support.
		/// Do not change the method contents inside the source code editor. The Forms designer might
		/// not be able to load this method if it was changed manually.
		/// </summary>
		private void InitializeComponent()
		{
			this.xToolStripMenuItem5 = new System.Windows.Forms.ToolStripMenuItem();
			this.mainTableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
			this.resetButton = new System.Windows.Forms.Button();
			this.button32 = new System.Windows.Forms.Button();
			this.button15 = new System.Windows.Forms.Button();
			this.button19 = new System.Windows.Forms.Button();
			this.button4 = new System.Windows.Forms.Button();
			this.button21 = new System.Windows.Forms.Button();
			this.button2 = new System.Windows.Forms.Button();
			this.button25 = new System.Windows.Forms.Button();
			this.button36 = new System.Windows.Forms.Button();
			this.button5 = new System.Windows.Forms.Button();
			this.button14 = new System.Windows.Forms.Button();
			this.button7 = new System.Windows.Forms.Button();
			this.button17 = new System.Windows.Forms.Button();
			this.button11 = new System.Windows.Forms.Button();
			this.button24 = new System.Windows.Forms.Button();
			this.button31 = new System.Windows.Forms.Button();
			this.button28 = new System.Windows.Forms.Button();
			this.button34 = new System.Windows.Forms.Button();
			this.button30 = new System.Windows.Forms.Button();
			this.button16 = new System.Windows.Forms.Button();
			this.button9 = new System.Windows.Forms.Button();
			this.button12 = new System.Windows.Forms.Button();
			this.button6 = new System.Windows.Forms.Button();
			this.button8 = new System.Windows.Forms.Button();
			this.button33 = new System.Windows.Forms.Button();
			this.button22 = new System.Windows.Forms.Button();
			this.button35 = new System.Windows.Forms.Button();
			this.button27 = new System.Windows.Forms.Button();
			this.button23 = new System.Windows.Forms.Button();
			this.button1 = new System.Windows.Forms.Button();
			this.button18 = new System.Windows.Forms.Button();
			this.button3 = new System.Windows.Forms.Button();
			this.button13 = new System.Windows.Forms.Button();
			this.button10 = new System.Windows.Forms.Button();
			this.button20 = new System.Windows.Forms.Button();
			this.button29 = new System.Windows.Forms.Button();
			this.button26 = new System.Windows.Forms.Button();
			this.xToolStripMenuItem6 = new System.Windows.Forms.ToolStripMenuItem();
			this.xToolStripMenuItem4 = new System.Windows.Forms.ToolStripMenuItem();
			this.xToolStripMenuItem7 = new System.Windows.Forms.ToolStripMenuItem();
			this.xToolStripMenuItem3 = new System.Windows.Forms.ToolStripMenuItem();
			this.setColorsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.xToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.xToolStripMenuItem1 = new System.Windows.Forms.ToolStripMenuItem();
			this.xToolStripMenuItem2 = new System.Windows.Forms.ToolStripMenuItem();
			this.xToolStripMenuItem8 = new System.Windows.Forms.ToolStripMenuItem();
			this.xToolStripMenuItem9 = new System.Windows.Forms.ToolStripMenuItem();
			this.helpToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
			this.aboutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.optionsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.alwaysOntopToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.undoToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.editToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.resetToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.newToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.mainMenuStrip = new System.Windows.Forms.MenuStrip();
			this.mainColorDialog = new System.Windows.Forms.ColorDialog();
			this.mainTableLayoutPanel.SuspendLayout();
			this.mainMenuStrip.SuspendLayout();
			this.SuspendLayout();
			// 
			// xToolStripMenuItem5
			// 
			this.xToolStripMenuItem5.Name = "xToolStripMenuItem5";
			this.xToolStripMenuItem5.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D6)));
			this.xToolStripMenuItem5.Size = new System.Drawing.Size(130, 22);
			this.xToolStripMenuItem5.Text = "&6x";
			// 
			// mainTableLayoutPanel
			// 
			this.mainTableLayoutPanel.ColumnCount = 6;
			this.mainTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
			this.mainTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
			this.mainTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
			this.mainTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
			this.mainTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
			this.mainTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
			this.mainTableLayoutPanel.Controls.Add(this.resetButton, 0, 6);
			this.mainTableLayoutPanel.Controls.Add(this.button32, 0, 0);
			this.mainTableLayoutPanel.Controls.Add(this.button15, 1, 0);
			this.mainTableLayoutPanel.Controls.Add(this.button19, 2, 0);
			this.mainTableLayoutPanel.Controls.Add(this.button4, 3, 0);
			this.mainTableLayoutPanel.Controls.Add(this.button21, 4, 0);
			this.mainTableLayoutPanel.Controls.Add(this.button2, 5, 0);
			this.mainTableLayoutPanel.Controls.Add(this.button25, 0, 1);
			this.mainTableLayoutPanel.Controls.Add(this.button36, 0, 2);
			this.mainTableLayoutPanel.Controls.Add(this.button5, 0, 3);
			this.mainTableLayoutPanel.Controls.Add(this.button14, 0, 4);
			this.mainTableLayoutPanel.Controls.Add(this.button7, 0, 5);
			this.mainTableLayoutPanel.Controls.Add(this.button17, 1, 1);
			this.mainTableLayoutPanel.Controls.Add(this.button11, 1, 2);
			this.mainTableLayoutPanel.Controls.Add(this.button24, 1, 3);
			this.mainTableLayoutPanel.Controls.Add(this.button31, 1, 4);
			this.mainTableLayoutPanel.Controls.Add(this.button28, 1, 5);
			this.mainTableLayoutPanel.Controls.Add(this.button34, 2, 1);
			this.mainTableLayoutPanel.Controls.Add(this.button30, 2, 2);
			this.mainTableLayoutPanel.Controls.Add(this.button16, 2, 3);
			this.mainTableLayoutPanel.Controls.Add(this.button9, 2, 4);
			this.mainTableLayoutPanel.Controls.Add(this.button12, 2, 5);
			this.mainTableLayoutPanel.Controls.Add(this.button6, 3, 1);
			this.mainTableLayoutPanel.Controls.Add(this.button8, 3, 2);
			this.mainTableLayoutPanel.Controls.Add(this.button33, 3, 3);
			this.mainTableLayoutPanel.Controls.Add(this.button22, 3, 4);
			this.mainTableLayoutPanel.Controls.Add(this.button35, 3, 5);
			this.mainTableLayoutPanel.Controls.Add(this.button27, 4, 1);
			this.mainTableLayoutPanel.Controls.Add(this.button23, 4, 2);
			this.mainTableLayoutPanel.Controls.Add(this.button1, 4, 3);
			this.mainTableLayoutPanel.Controls.Add(this.button18, 4, 4);
			this.mainTableLayoutPanel.Controls.Add(this.button3, 4, 5);
			this.mainTableLayoutPanel.Controls.Add(this.button13, 5, 1);
			this.mainTableLayoutPanel.Controls.Add(this.button10, 5, 2);
			this.mainTableLayoutPanel.Controls.Add(this.button20, 5, 3);
			this.mainTableLayoutPanel.Controls.Add(this.button29, 5, 4);
			this.mainTableLayoutPanel.Controls.Add(this.button26, 5, 5);
			this.mainTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
			this.mainTableLayoutPanel.Location = new System.Drawing.Point(0, 24);
			this.mainTableLayoutPanel.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.mainTableLayoutPanel.Name = "mainTableLayoutPanel";
			this.mainTableLayoutPanel.RowCount = 7;
			this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28571F));
			this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28572F));
			this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28572F));
			this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28572F));
			this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28571F));
			this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28572F));
			this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28572F));
			this.mainTableLayoutPanel.Size = new System.Drawing.Size(377, 351);
			this.mainTableLayoutPanel.TabIndex = 10;
			// 
			// resetButton
			// 
			this.resetButton.BackColor = System.Drawing.Color.MidnightBlue;
			this.mainTableLayoutPanel.SetColumnSpan(this.resetButton, 7);
			this.resetButton.Dock = System.Windows.Forms.DockStyle.Fill;
			this.resetButton.Location = new System.Drawing.Point(1, 301);
			this.resetButton.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.resetButton.Name = "resetButton";
			this.resetButton.Size = new System.Drawing.Size(375, 49);
			this.resetButton.TabIndex = 0;
			this.resetButton.Text = "&Reset";
			this.resetButton.UseVisualStyleBackColor = false;
			// 
			// button32
			// 
			this.button32.BackColor = System.Drawing.Color.Red;
			this.button32.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button32.Location = new System.Drawing.Point(1, 1);
			this.button32.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button32.Name = "button32";
			this.button32.Size = new System.Drawing.Size(60, 48);
			this.button32.TabIndex = 1;
			this.button32.Text = "32";
			this.button32.UseVisualStyleBackColor = false;
			// 
			// button15
			// 
			this.button15.BackColor = System.Drawing.Color.Black;
			this.button15.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button15.Location = new System.Drawing.Point(63, 1);
			this.button15.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button15.Name = "button15";
			this.button15.Size = new System.Drawing.Size(60, 48);
			this.button15.TabIndex = 2;
			this.button15.Text = "15";
			this.button15.UseVisualStyleBackColor = false;
			// 
			// button19
			// 
			this.button19.BackColor = System.Drawing.Color.Red;
			this.button19.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button19.Location = new System.Drawing.Point(125, 1);
			this.button19.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button19.Name = "button19";
			this.button19.Size = new System.Drawing.Size(60, 48);
			this.button19.TabIndex = 3;
			this.button19.Text = "19";
			this.button19.UseVisualStyleBackColor = false;
			// 
			// button4
			// 
			this.button4.BackColor = System.Drawing.Color.Black;
			this.button4.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button4.Location = new System.Drawing.Point(187, 1);
			this.button4.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button4.Name = "button4";
			this.button4.Size = new System.Drawing.Size(60, 48);
			this.button4.TabIndex = 4;
			this.button4.Text = "4";
			this.button4.UseVisualStyleBackColor = false;
			// 
			// button21
			// 
			this.button21.BackColor = System.Drawing.Color.Red;
			this.button21.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button21.Location = new System.Drawing.Point(249, 1);
			this.button21.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button21.Name = "button21";
			this.button21.Size = new System.Drawing.Size(60, 48);
			this.button21.TabIndex = 5;
			this.button21.Text = "21";
			this.button21.UseVisualStyleBackColor = false;
			// 
			// button2
			// 
			this.button2.BackColor = System.Drawing.Color.Black;
			this.button2.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button2.Location = new System.Drawing.Point(311, 1);
			this.button2.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button2.Name = "button2";
			this.button2.Size = new System.Drawing.Size(65, 48);
			this.button2.TabIndex = 6;
			this.button2.Text = "2";
			this.button2.UseVisualStyleBackColor = false;
			// 
			// button25
			// 
			this.button25.BackColor = System.Drawing.Color.Red;
			this.button25.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button25.Location = new System.Drawing.Point(1, 51);
			this.button25.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button25.Name = "button25";
			this.button25.Size = new System.Drawing.Size(60, 48);
			this.button25.TabIndex = 7;
			this.button25.Text = "25";
			this.button25.UseVisualStyleBackColor = false;
			// 
			// button36
			// 
			this.button36.BackColor = System.Drawing.Color.Red;
			this.button36.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button36.Location = new System.Drawing.Point(1, 101);
			this.button36.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button36.Name = "button36";
			this.button36.Size = new System.Drawing.Size(60, 48);
			this.button36.TabIndex = 8;
			this.button36.Text = "36";
			this.button36.UseVisualStyleBackColor = false;
			// 
			// button5
			// 
			this.button5.BackColor = System.Drawing.Color.Red;
			this.button5.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button5.Location = new System.Drawing.Point(1, 151);
			this.button5.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button5.Name = "button5";
			this.button5.Size = new System.Drawing.Size(60, 48);
			this.button5.TabIndex = 9;
			this.button5.Text = "5";
			this.button5.UseVisualStyleBackColor = false;
			// 
			// button14
			// 
			this.button14.BackColor = System.Drawing.Color.Red;
			this.button14.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button14.Location = new System.Drawing.Point(1, 201);
			this.button14.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button14.Name = "button14";
			this.button14.Size = new System.Drawing.Size(60, 48);
			this.button14.TabIndex = 10;
			this.button14.Text = "14";
			this.button14.UseVisualStyleBackColor = false;
			// 
			// button7
			// 
			this.button7.BackColor = System.Drawing.Color.Red;
			this.button7.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button7.Location = new System.Drawing.Point(1, 251);
			this.button7.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button7.Name = "button7";
			this.button7.Size = new System.Drawing.Size(60, 48);
			this.button7.TabIndex = 11;
			this.button7.Text = "7";
			this.button7.UseVisualStyleBackColor = false;
			// 
			// button17
			// 
			this.button17.BackColor = System.Drawing.Color.Black;
			this.button17.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button17.Location = new System.Drawing.Point(63, 51);
			this.button17.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button17.Name = "button17";
			this.button17.Size = new System.Drawing.Size(60, 48);
			this.button17.TabIndex = 12;
			this.button17.Text = "17";
			this.button17.UseVisualStyleBackColor = false;
			// 
			// button11
			// 
			this.button11.BackColor = System.Drawing.Color.Black;
			this.button11.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button11.Location = new System.Drawing.Point(63, 101);
			this.button11.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button11.Name = "button11";
			this.button11.Size = new System.Drawing.Size(60, 48);
			this.button11.TabIndex = 13;
			this.button11.Text = "11";
			this.button11.UseVisualStyleBackColor = false;
			// 
			// button24
			// 
			this.button24.BackColor = System.Drawing.Color.Black;
			this.button24.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button24.Location = new System.Drawing.Point(63, 151);
			this.button24.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button24.Name = "button24";
			this.button24.Size = new System.Drawing.Size(60, 48);
			this.button24.TabIndex = 14;
			this.button24.Text = "24";
			this.button24.UseVisualStyleBackColor = false;
			// 
			// button31
			// 
			this.button31.BackColor = System.Drawing.Color.Black;
			this.button31.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button31.Location = new System.Drawing.Point(63, 201);
			this.button31.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button31.Name = "button31";
			this.button31.Size = new System.Drawing.Size(60, 48);
			this.button31.TabIndex = 15;
			this.button31.Text = "31";
			this.button31.UseVisualStyleBackColor = false;
			// 
			// button28
			// 
			this.button28.BackColor = System.Drawing.Color.Black;
			this.button28.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button28.Location = new System.Drawing.Point(63, 251);
			this.button28.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button28.Name = "button28";
			this.button28.Size = new System.Drawing.Size(60, 48);
			this.button28.TabIndex = 16;
			this.button28.Text = "28";
			this.button28.UseVisualStyleBackColor = false;
			// 
			// button34
			// 
			this.button34.BackColor = System.Drawing.Color.Red;
			this.button34.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button34.Location = new System.Drawing.Point(125, 51);
			this.button34.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button34.Name = "button34";
			this.button34.Size = new System.Drawing.Size(60, 48);
			this.button34.TabIndex = 17;
			this.button34.Text = "34";
			this.button34.UseVisualStyleBackColor = false;
			// 
			// button30
			// 
			this.button30.BackColor = System.Drawing.Color.Red;
			this.button30.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button30.Location = new System.Drawing.Point(125, 101);
			this.button30.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button30.Name = "button30";
			this.button30.Size = new System.Drawing.Size(60, 48);
			this.button30.TabIndex = 18;
			this.button30.Text = "30";
			this.button30.UseVisualStyleBackColor = false;
			// 
			// button16
			// 
			this.button16.BackColor = System.Drawing.Color.Red;
			this.button16.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button16.Location = new System.Drawing.Point(125, 151);
			this.button16.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button16.Name = "button16";
			this.button16.Size = new System.Drawing.Size(60, 48);
			this.button16.TabIndex = 19;
			this.button16.Text = "16";
			this.button16.UseVisualStyleBackColor = false;
			// 
			// button9
			// 
			this.button9.BackColor = System.Drawing.Color.Red;
			this.button9.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button9.Location = new System.Drawing.Point(125, 201);
			this.button9.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button9.Name = "button9";
			this.button9.Size = new System.Drawing.Size(60, 48);
			this.button9.TabIndex = 20;
			this.button9.Text = "9";
			this.button9.UseVisualStyleBackColor = false;
			// 
			// button12
			// 
			this.button12.BackColor = System.Drawing.Color.Red;
			this.button12.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button12.Location = new System.Drawing.Point(125, 251);
			this.button12.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button12.Name = "button12";
			this.button12.Size = new System.Drawing.Size(60, 48);
			this.button12.TabIndex = 21;
			this.button12.Text = "12";
			this.button12.UseVisualStyleBackColor = false;
			// 
			// button6
			// 
			this.button6.BackColor = System.Drawing.Color.Black;
			this.button6.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button6.Location = new System.Drawing.Point(187, 51);
			this.button6.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button6.Name = "button6";
			this.button6.Size = new System.Drawing.Size(60, 48);
			this.button6.TabIndex = 22;
			this.button6.Text = "6";
			this.button6.UseVisualStyleBackColor = false;
			// 
			// button8
			// 
			this.button8.BackColor = System.Drawing.Color.Black;
			this.button8.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button8.Location = new System.Drawing.Point(187, 101);
			this.button8.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button8.Name = "button8";
			this.button8.Size = new System.Drawing.Size(60, 48);
			this.button8.TabIndex = 23;
			this.button8.Text = "8";
			this.button8.UseVisualStyleBackColor = false;
			// 
			// button33
			// 
			this.button33.BackColor = System.Drawing.Color.Black;
			this.button33.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button33.Location = new System.Drawing.Point(187, 151);
			this.button33.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button33.Name = "button33";
			this.button33.Size = new System.Drawing.Size(60, 48);
			this.button33.TabIndex = 24;
			this.button33.Text = "33";
			this.button33.UseVisualStyleBackColor = false;
			// 
			// button22
			// 
			this.button22.BackColor = System.Drawing.Color.Black;
			this.button22.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button22.Location = new System.Drawing.Point(187, 201);
			this.button22.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button22.Name = "button22";
			this.button22.Size = new System.Drawing.Size(60, 48);
			this.button22.TabIndex = 25;
			this.button22.Text = "22";
			this.button22.UseVisualStyleBackColor = false;
			// 
			// button35
			// 
			this.button35.BackColor = System.Drawing.Color.Black;
			this.button35.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button35.Location = new System.Drawing.Point(187, 251);
			this.button35.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button35.Name = "button35";
			this.button35.Size = new System.Drawing.Size(60, 48);
			this.button35.TabIndex = 26;
			this.button35.Text = "35";
			this.button35.UseVisualStyleBackColor = false;
			// 
			// button27
			// 
			this.button27.BackColor = System.Drawing.Color.Red;
			this.button27.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button27.Location = new System.Drawing.Point(249, 51);
			this.button27.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button27.Name = "button27";
			this.button27.Size = new System.Drawing.Size(60, 48);
			this.button27.TabIndex = 27;
			this.button27.Text = "27";
			this.button27.UseVisualStyleBackColor = false;
			// 
			// button23
			// 
			this.button23.BackColor = System.Drawing.Color.Red;
			this.button23.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button23.Location = new System.Drawing.Point(249, 101);
			this.button23.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button23.Name = "button23";
			this.button23.Size = new System.Drawing.Size(60, 48);
			this.button23.TabIndex = 28;
			this.button23.Text = "23";
			this.button23.UseVisualStyleBackColor = false;
			// 
			// button1
			// 
			this.button1.BackColor = System.Drawing.Color.Red;
			this.button1.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button1.Location = new System.Drawing.Point(249, 151);
			this.button1.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button1.Name = "button1";
			this.button1.Size = new System.Drawing.Size(60, 48);
			this.button1.TabIndex = 29;
			this.button1.Text = "1";
			this.button1.UseVisualStyleBackColor = false;
			// 
			// button18
			// 
			this.button18.BackColor = System.Drawing.Color.Red;
			this.button18.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button18.Location = new System.Drawing.Point(249, 201);
			this.button18.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button18.Name = "button18";
			this.button18.Size = new System.Drawing.Size(60, 48);
			this.button18.TabIndex = 30;
			this.button18.Text = "18";
			this.button18.UseVisualStyleBackColor = false;
			// 
			// button3
			// 
			this.button3.BackColor = System.Drawing.Color.Red;
			this.button3.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button3.Location = new System.Drawing.Point(249, 251);
			this.button3.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button3.Name = "button3";
			this.button3.Size = new System.Drawing.Size(60, 48);
			this.button3.TabIndex = 31;
			this.button3.Text = "3";
			this.button3.UseVisualStyleBackColor = false;
			// 
			// button13
			// 
			this.button13.BackColor = System.Drawing.Color.Black;
			this.button13.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button13.Location = new System.Drawing.Point(311, 51);
			this.button13.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button13.Name = "button13";
			this.button13.Size = new System.Drawing.Size(65, 48);
			this.button13.TabIndex = 32;
			this.button13.Text = "13";
			this.button13.UseVisualStyleBackColor = false;
			// 
			// button10
			// 
			this.button10.BackColor = System.Drawing.Color.Black;
			this.button10.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button10.Location = new System.Drawing.Point(311, 101);
			this.button10.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button10.Name = "button10";
			this.button10.Size = new System.Drawing.Size(65, 48);
			this.button10.TabIndex = 33;
			this.button10.Text = "10";
			this.button10.UseVisualStyleBackColor = false;
			// 
			// button20
			// 
			this.button20.BackColor = System.Drawing.Color.Black;
			this.button20.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button20.Location = new System.Drawing.Point(311, 151);
			this.button20.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button20.Name = "button20";
			this.button20.Size = new System.Drawing.Size(65, 48);
			this.button20.TabIndex = 34;
			this.button20.Text = "20";
			this.button20.UseVisualStyleBackColor = false;
			// 
			// button29
			// 
			this.button29.BackColor = System.Drawing.Color.Black;
			this.button29.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button29.Location = new System.Drawing.Point(311, 201);
			this.button29.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button29.Name = "button29";
			this.button29.Size = new System.Drawing.Size(65, 48);
			this.button29.TabIndex = 35;
			this.button29.Text = "29";
			this.button29.UseVisualStyleBackColor = false;
			// 
			// button26
			// 
			this.button26.BackColor = System.Drawing.Color.Black;
			this.button26.Dock = System.Windows.Forms.DockStyle.Fill;
			this.button26.Location = new System.Drawing.Point(311, 251);
			this.button26.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
			this.button26.Name = "button26";
			this.button26.Size = new System.Drawing.Size(65, 48);
			this.button26.TabIndex = 36;
			this.button26.Text = "26";
			this.button26.UseVisualStyleBackColor = false;
			// 
			// xToolStripMenuItem6
			// 
			this.xToolStripMenuItem6.Name = "xToolStripMenuItem6";
			this.xToolStripMenuItem6.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D7)));
			this.xToolStripMenuItem6.Size = new System.Drawing.Size(130, 22);
			this.xToolStripMenuItem6.Text = "&7x";
			// 
			// xToolStripMenuItem4
			// 
			this.xToolStripMenuItem4.Name = "xToolStripMenuItem4";
			this.xToolStripMenuItem4.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D5)));
			this.xToolStripMenuItem4.Size = new System.Drawing.Size(130, 22);
			this.xToolStripMenuItem4.Text = "5x";
			// 
			// xToolStripMenuItem7
			// 
			this.xToolStripMenuItem7.Name = "xToolStripMenuItem7";
			this.xToolStripMenuItem7.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D8)));
			this.xToolStripMenuItem7.Size = new System.Drawing.Size(130, 22);
			this.xToolStripMenuItem7.Text = "&8x";
			// 
			// xToolStripMenuItem3
			// 
			this.xToolStripMenuItem3.Name = "xToolStripMenuItem3";
			this.xToolStripMenuItem3.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D4)));
			this.xToolStripMenuItem3.Size = new System.Drawing.Size(130, 22);
			this.xToolStripMenuItem3.Text = "&4x";
			// 
			// setColorsToolStripMenuItem
			// 
			this.setColorsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
									this.xToolStripMenuItem,
									this.xToolStripMenuItem1,
									this.xToolStripMenuItem2,
									this.xToolStripMenuItem3,
									this.xToolStripMenuItem4,
									this.xToolStripMenuItem5,
									this.xToolStripMenuItem6,
									this.xToolStripMenuItem7,
									this.xToolStripMenuItem8,
									this.xToolStripMenuItem9});
			this.setColorsToolStripMenuItem.Name = "setColorsToolStripMenuItem";
			this.setColorsToolStripMenuItem.Size = new System.Drawing.Size(180, 22);
			this.setColorsToolStripMenuItem.Text = "&Set colors";
			// 
			// xToolStripMenuItem
			// 
			this.xToolStripMenuItem.Name = "xToolStripMenuItem";
			this.xToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D1)));
			this.xToolStripMenuItem.Size = new System.Drawing.Size(130, 22);
			this.xToolStripMenuItem.Text = "&1x";
			// 
			// xToolStripMenuItem1
			// 
			this.xToolStripMenuItem1.Name = "xToolStripMenuItem1";
			this.xToolStripMenuItem1.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D2)));
			this.xToolStripMenuItem1.Size = new System.Drawing.Size(130, 22);
			this.xToolStripMenuItem1.Text = "&2x";
			// 
			// xToolStripMenuItem2
			// 
			this.xToolStripMenuItem2.Name = "xToolStripMenuItem2";
			this.xToolStripMenuItem2.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D3)));
			this.xToolStripMenuItem2.Size = new System.Drawing.Size(130, 22);
			this.xToolStripMenuItem2.Text = "&3x";
			// 
			// xToolStripMenuItem8
			// 
			this.xToolStripMenuItem8.Name = "xToolStripMenuItem8";
			this.xToolStripMenuItem8.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D9)));
			this.xToolStripMenuItem8.Size = new System.Drawing.Size(130, 22);
			this.xToolStripMenuItem8.Text = "9x";
			// 
			// xToolStripMenuItem9
			// 
			this.xToolStripMenuItem9.Name = "xToolStripMenuItem9";
			this.xToolStripMenuItem9.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D0)));
			this.xToolStripMenuItem9.Size = new System.Drawing.Size(130, 22);
			this.xToolStripMenuItem9.Text = "1&0x";
			// 
			// helpToolStripMenuItem
			// 
			this.helpToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
									this.toolStripSeparator1,
									this.aboutToolStripMenuItem});
			this.helpToolStripMenuItem.Name = "helpToolStripMenuItem";
			this.helpToolStripMenuItem.Size = new System.Drawing.Size(40, 22);
			this.helpToolStripMenuItem.Text = "&Help";
			// 
			// toolStripSeparator1
			// 
			this.toolStripSeparator1.Name = "toolStripSeparator1";
			this.toolStripSeparator1.Size = new System.Drawing.Size(151, 6);
			// 
			// aboutToolStripMenuItem
			// 
			this.aboutToolStripMenuItem.Name = "aboutToolStripMenuItem";
			this.aboutToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.A)));
			this.aboutToolStripMenuItem.Size = new System.Drawing.Size(154, 22);
			this.aboutToolStripMenuItem.Text = "&About...";
			// 
			// optionsToolStripMenuItem
			// 
			this.optionsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
									this.setColorsToolStripMenuItem,
									this.alwaysOntopToolStripMenuItem});
			this.optionsToolStripMenuItem.Name = "optionsToolStripMenuItem";
			this.optionsToolStripMenuItem.Size = new System.Drawing.Size(56, 22);
			this.optionsToolStripMenuItem.Text = "&Options";
			// 
			// alwaysOntopToolStripMenuItem
			// 
			this.alwaysOntopToolStripMenuItem.Name = "alwaysOntopToolStripMenuItem";
			this.alwaysOntopToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.T)));
			this.alwaysOntopToolStripMenuItem.Size = new System.Drawing.Size(180, 22);
			this.alwaysOntopToolStripMenuItem.Text = "Always on &top";
			// 
			// undoToolStripMenuItem
			// 
			this.undoToolStripMenuItem.Name = "undoToolStripMenuItem";
			this.undoToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Z)));
			this.undoToolStripMenuItem.Size = new System.Drawing.Size(141, 22);
			this.undoToolStripMenuItem.Text = "&Undo";
			// 
			// editToolStripMenuItem
			// 
			this.editToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
									this.undoToolStripMenuItem,
									this.resetToolStripMenuItem});
			this.editToolStripMenuItem.Name = "editToolStripMenuItem";
			this.editToolStripMenuItem.Size = new System.Drawing.Size(37, 22);
			this.editToolStripMenuItem.Text = "&Edit";
			// 
			// resetToolStripMenuItem
			// 
			this.resetToolStripMenuItem.Name = "resetToolStripMenuItem";
			this.resetToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.R)));
			this.resetToolStripMenuItem.Size = new System.Drawing.Size(141, 22);
			this.resetToolStripMenuItem.Text = "&Reset";
			// 
			// newToolStripMenuItem
			// 
			this.newToolStripMenuItem.Name = "newToolStripMenuItem";
			this.newToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.N)));
			this.newToolStripMenuItem.Size = new System.Drawing.Size(134, 22);
			this.newToolStripMenuItem.Text = "&New";
			// 
			// fileToolStripMenuItem
			// 
			this.fileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
									this.newToolStripMenuItem});
			this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
			this.fileToolStripMenuItem.Size = new System.Drawing.Size(35, 22);
			this.fileToolStripMenuItem.Text = "&File";
			// 
			// mainMenuStrip
			// 
			this.mainMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
									this.fileToolStripMenuItem,
									this.editToolStripMenuItem,
									this.optionsToolStripMenuItem,
									this.helpToolStripMenuItem});
			this.mainMenuStrip.Location = new System.Drawing.Point(0, 0);
			this.mainMenuStrip.Name = "mainMenuStrip";
			this.mainMenuStrip.Padding = new System.Windows.Forms.Padding(1, 1, 0, 1);
			this.mainMenuStrip.Size = new System.Drawing.Size(377, 24);
			this.mainMenuStrip.TabIndex = 9;
			this.mainMenuStrip.Text = "menuStrip1";
			// 
			// MainForm
			// 
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
			this.BackColor = System.Drawing.Color.DarkGreen;
			this.ClientSize = new System.Drawing.Size(377, 375);
			this.Controls.Add(this.mainTableLayoutPanel);
			this.Controls.Add(this.mainMenuStrip);
			this.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.ForeColor = System.Drawing.Color.White;
			this.Name = "MainForm";
			this.Text = "Matrix_51__50__32_Input_32_Tracker";
			this.mainTableLayoutPanel.ResumeLayout(false);
			this.mainMenuStrip.ResumeLayout(false);
			this.mainMenuStrip.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();
		}
		private System.Windows.Forms.ColorDialog mainColorDialog;
		private System.Windows.Forms.MenuStrip mainMenuStrip;
		private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;
		private System.Windows.Forms.ToolStripMenuItem newToolStripMenuItem;
		private System.Windows.Forms.ToolStripMenuItem resetToolStripMenuItem;
		private System.Windows.Forms.ToolStripMenuItem editToolStripMenuItem;
		private System.Windows.Forms.ToolStripMenuItem undoToolStripMenuItem;
		private System.Windows.Forms.ToolStripMenuItem alwaysOntopToolStripMenuItem;
		private System.Windows.Forms.ToolStripMenuItem optionsToolStripMenuItem;
		private System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem;
		private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
		private System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem;
		private System.Windows.Forms.ToolStripMenuItem xToolStripMenuItem9;
		private System.Windows.Forms.ToolStripMenuItem xToolStripMenuItem8;
		private System.Windows.Forms.ToolStripMenuItem xToolStripMenuItem2;
		private System.Windows.Forms.ToolStripMenuItem xToolStripMenuItem1;
		private System.Windows.Forms.ToolStripMenuItem xToolStripMenuItem;
		private System.Windows.Forms.ToolStripMenuItem setColorsToolStripMenuItem;
		private System.Windows.Forms.ToolStripMenuItem xToolStripMenuItem3;
		private System.Windows.Forms.ToolStripMenuItem xToolStripMenuItem7;
		private System.Windows.Forms.ToolStripMenuItem xToolStripMenuItem4;
		private System.Windows.Forms.ToolStripMenuItem xToolStripMenuItem6;
		private System.Windows.Forms.Button button26;
		private System.Windows.Forms.Button button29;
		private System.Windows.Forms.Button button20;
		private System.Windows.Forms.Button button10;
		private System.Windows.Forms.Button button13;
		private System.Windows.Forms.Button button3;
		private System.Windows.Forms.Button button18;
		private System.Windows.Forms.Button button1;
		private System.Windows.Forms.Button button23;
		private System.Windows.Forms.Button button27;
		private System.Windows.Forms.Button button35;
		private System.Windows.Forms.Button button22;
		private System.Windows.Forms.Button button33;
		private System.Windows.Forms.Button button8;
		private System.Windows.Forms.Button button6;
		private System.Windows.Forms.Button button12;
		private System.Windows.Forms.Button button9;
		private System.Windows.Forms.Button button16;
		private System.Windows.Forms.Button button30;
		private System.Windows.Forms.Button button34;
		private System.Windows.Forms.Button button28;
		private System.Windows.Forms.Button button31;
		private System.Windows.Forms.Button button24;
		private System.Windows.Forms.Button button11;
		private System.Windows.Forms.Button button17;
		private System.Windows.Forms.Button button7;
		private System.Windows.Forms.Button button14;
		private System.Windows.Forms.Button button5;
		private System.Windows.Forms.Button button36;
		private System.Windows.Forms.Button button25;
		private System.Windows.Forms.Button button2;
		private System.Windows.Forms.Button button21;
		private System.Windows.Forms.Button button4;
		private System.Windows.Forms.Button button19;
		private System.Windows.Forms.Button button15;
		private System.Windows.Forms.Button button32;
		private System.Windows.Forms.Button resetButton;
		private System.Windows.Forms.TableLayoutPanel mainTableLayoutPanel;
		private System.Windows.Forms.ToolStripMenuItem xToolStripMenuItem5;
	}
}
